### ISSUE TITLE
make install -> no rule to make target "install"

### ISSUE THREAD

**Issue by tamasgal** [eisvogel-project/Eisvogel#53]
Sorry to bother you again, I successfully built Eisvogel (got a warning about openmpi libs though, we will see if it causes problems later), but the `make install` is not working. I used the following configuration:

```
(base) ✔ /home/vault/capn/shared/apps/alma8/apps/Eisvogel/src/build [main|✔]
17:50 $ cmake -DBUILD_TESTS=ON -DBUILD_EXAMPLES=ON -DBUILD_MEEP=ON -DCMAKE_INSTALL_PREFIX=/home/vault/capn/shared/apps/alma8/apps/Eisvogel/8f5fd566 ..
```

and then got this:

```
...
...
Consolidate compiler generated dependencies of target testAskaryan
[ 94%] Built target testAskaryan
Consolidate compiler generated dependencies of target testCherenkov
[100%] Built target testCherenkov
(base) ✔ /home/vault/capn/shared/apps/alma8/apps/Eisvogel/src/build [main|✔]
17:49 $ make install
make: *** No rule to make target 'install'.  Stop.
```

In the docs, the `make install` step is only mentioned when building Eisvogel with Corsika, is that maybe the reason?

**Comment by philippwindischhofer** [comment]
Hi! Yes, indeed, Eisvogel being header-only, there is no need to "install" anything as long as you're only building the examples. The `BUILD_CORSIKA` switch builds a shared library that C8 can be linked against.

**Comment by tamasgal** [comment]
OK understood!

**Comment by cozzyd** [comment]
It may still make sense to copy the headers some place, no? That's usually what the install target for header only libraries does (and maybe a cmake  module file)

**Comment by philippwindischhofer** [comment]
Yes, you're right, it makes sense ... just so far there was no need to export the headers as the only executables using them are "internal" ones.
